-- -- Wed Apr 13 1:01:35
UPDATE `item_template` SET `maxcount` = 3 WHERE `entry` = 1315
-- -- Wed Apr 13 1:01:35
UPDATE `item_template` SET `AllowableRace` = 1 WHERE `entry` = 1315
-- -- Wed Apr 13 1:01:35
UPDATE `item_template` SET `AllowableClass` = 1 WHERE `entry` = 1315
-- -- Wed Apr 13 1:02:40
UPDATE `item_template` SET `maxcount` = 0 WHERE `entry` = 1315
-- -- Wed Apr 13 1:11:06
UPDATE `item_template` SET `maxcount` = 3 WHERE `entry` = 1315
-- -- Wed Apr 13 1:11:30
UPDATE `item_template` SET `Quality` = 0 WHERE `entry` = 1315
-- -- Wed Apr 13 1:11:30
UPDATE `item_template` SET `InventoryType` = 0 WHERE `entry` = 1315
-- -- Wed Apr 13 1:11:30
UPDATE `item_template` SET `maxcount` = 0 WHERE `entry` = 1315
-- -- Wed Apr 13 1:11:39
UPDATE `item_template` SET `ScalingStatValue` = 12589 WHERE `entry` = 1315
-- -- Wed Apr 13 1:11:45
UPDATE `item_template` SET `ScalingStatValue` = 0 WHERE `entry` = 1315
-- -- Wed Apr 13 1:26:59
UPDATE `item_template` SET `AllowableRace` = -1 WHERE `entry` = 1315
-- -- Wed Apr 13 1:27:05
UPDATE `item_template` SET `AllowableClass` = -1 WHERE `entry` = 1315
-- -- Wed Apr 13 1:27:46
UPDATE `item_template` SET `sheath` = 6 WHERE `entry` = 1315
-- -- Wed Apr 13 1:27:55
UPDATE `item_template` SET `sheath` = 0 WHERE `entry` = 1315
-- -- Wed Apr 13 1:28:12
UPDATE `item_template` SET `InventoryType` = 2 WHERE `entry` = 1315
-- -- Wed Apr 13 1:28:27
UPDATE `item_template` SET `Quality` = 4 WHERE `entry` = 1315
-- -- Wed Apr 13 7:32:41
UPDATE `item_template` SET `sheath` = 4 WHERE `entry` = 18583
