<?php
    $questflags[1]="STAY_ALIVE";
    $questflags[2]="PARTY_ACCEPT";
    $questflags[3]="EXPLORATION";
    $questflags[4]="SHAREABLE";
    $questflags[5]="NOTUSED";
    $questflags[6]="EPIC";
    $questflags[7]="RAID";
    $questflags[8]="TBC";
    $questflags[9]="UNK2";
    $questflags[10]="HIDDEN_REWARDS";
    $questflags[11]="AUTO_REWARDED";
    $questflags[12]="TBC_RACES";
    $questflags[13]="DAILY";
    $questflags[14]="FLAGS_PVP";
    $questflags[15]="UNK4";
    $questflags[16]="WEEKLY";
    $questflags[17]="AUTOCOMPLETE";
    $questflags[18]="UNK5";
    $questflags[19]="UNK6";
    $questflags[20]="AUTO_ACCEPT";
?>